name: __apptainer__
channels:
  - nvidia
  - pytorch
  - plotly
  # - huggingface
  - conda-forge
dependencies:
  - python==3.12
  - pip
  - plotly
  # - ipywidgets
  - tqdm
  - seaborn
  - pandas
  - numpy
  - scikit-learn
  # - pytorch
  # - torchvision
  # - torchaudio
  # - pytorch-cuda=12.1
  # - torchmetrics 
  - pytorch==2.5.1
  - torchvision==0.20.1
  - torchaudio==2.5.1
  - pytorch-cuda=12.4
  # - lightning
  # - accelerate
  # - safetensors
  # - diffusers
  # - transformers
  # - datasets
  # - deepspeed
  # - opencv
  - pillow
  - spacy
  - scipy
  # - onnx
  # - fastai
  # - wandb
  # - pycocotools
  - tqdm 
  - pip:
    - -r requirements.txt
